import { toDoModel } from './toDoModel';

export const toDoData: toDoModel[] = [
  {
    id: 1,
    responsaveis: ['Ana', 'Carlos'],
    urgencia: 'ALTA',
    status: 'PENDENTE',
    titulo: 'Implementar autenticação',
    descricao: 'Adicionar autenticação de usuário ao sistema.',
    previsaoEntrega: new Date('2025-08-25'),
    dataInicio: new Date('2025-08-20'),
    dataEntrega: new Date('2025-08-25'),
  },
  {
    id: 2,
    responsaveis: ['Bruno'],
    urgencia: 'MEDIA',
    status: 'EM EXECUÇÃO',
    titulo: 'Criar página de dashboard',
    descricao: 'Desenvolver o dashboard principal.',
    previsaoEntrega: new Date('2025-08-28'),
    dataInicio: new Date('2025-08-22'),
    dataEntrega: new Date('2025-08-28'),
  },
  {
    id: 3,
    responsaveis: ['Carla', 'Eduardo'],
    urgencia: 'BAIXA',
    status: 'REVISÃO PENDENTE',
    titulo: 'Ajustar layout mobile',
    descricao: 'Melhorar responsividade para dispositivos móveis.',
    previsaoEntrega: new Date('2025-08-30'),
    dataInicio: new Date('2025-08-21'),
    dataEntrega: new Date('2025-08-29'),
  },
  {
    id: 4,
    responsaveis: ['Fernanda'],
    urgencia: 'PRIORIDADE',
    status: 'CONCLUÍDA',
    titulo: 'Corrigir bug no login',
    descricao: 'Erro ao tentar logar com senha incorreta.',
    previsaoEntrega: new Date('2025-08-23'),
    dataInicio: new Date('2025-08-20'),
    dataEntrega: new Date('2025-08-22'),
  },
  {
    id: 5,
    responsaveis: ['Gabriel', 'Helena'],
    urgencia: 'MEDIA',
    status: 'APROVADA',
    titulo: 'Atualizar documentação',
    descricao: 'Revisar e atualizar documentação do projeto.',
    previsaoEntrega: new Date('2025-08-27'),
    dataInicio: new Date('2025-08-23'),
    dataEntrega: new Date('2025-08-26'),
  },
  {
    id: 6,
    responsaveis: ['Isabela'],
    urgencia: 'ALTA',
    status: 'CANCELADA',
    titulo: 'Integrar API de pagamentos',
    descricao: 'Adicionar integração com gateway de pagamento.',
    previsaoEntrega: new Date('2025-09-01'),
    dataInicio: new Date('2025-08-24'),
    dataEntrega: new Date('2025-08-30'),
  },
  {
    id: 7,
    responsaveis: ['João', 'Lucas'],
    urgencia: 'BAIXA',
    status: 'PENDENTE',
    titulo: 'Criar testes unitários',
    descricao: 'Cobrir componentes principais com testes.',
    previsaoEntrega: new Date('2025-09-02'),
    dataInicio: new Date('2025-08-25'),
    dataEntrega: new Date('2025-09-01'),
  },
  {
    id: 8,
    responsaveis: ['Marina'],
    urgencia: 'MEDIA',
    status: 'EM EXECUÇÃO',
    titulo: 'Refatorar serviço de usuários',
    descricao: 'Melhorar performance do serviço de usuários.',
    previsaoEntrega: new Date('2025-08-29'),
    dataInicio: new Date('2025-08-24'),
    dataEntrega: new Date('2025-08-29'),
  },
  {
    id: 9,
    responsaveis: ['Nina', 'Otávio'],
    urgencia: 'PRIORIDADE',
    status: 'REVISÃO PENDENTE',
    titulo: 'Ajustar permissões de acesso',
    descricao: 'Corrigir regras de permissão para diferentes perfis.',
    previsaoEntrega: new Date('2025-08-31'),
    dataInicio: new Date('2025-08-26'),
    dataEntrega: new Date('2025-08-30'),
  },
  {
    id: 10,
    responsaveis: ['Paulo'],
    urgencia: 'ALTA',
    status: 'CONCLUÍDA',
    titulo: 'Implementar logout automático',
    descricao: 'Logout automático após inatividade.',
    previsaoEntrega: new Date('2025-08-27'),
    dataInicio: new Date('2025-08-22'),
    dataEntrega: new Date('2025-08-27'),
  },
  {
    id: 11,
    responsaveis: ['Quésia', 'Rafael'],
    urgencia: 'MEDIA',
    status: 'APROVADA',
    titulo: 'Adicionar logs de auditoria',
    descricao: 'Registrar ações dos usuários no sistema.',
    previsaoEntrega: new Date('2025-09-03'),
    dataInicio: new Date('2025-08-27'),
    dataEntrega: new Date('2025-09-02'),
  },
  {
    id: 12,
    responsaveis: ['Sofia'],
    urgencia: 'BAIXA',
    status: 'CANCELADA',
    titulo: 'Criar página de configurações',
    descricao: 'Permitir que usuários alterem preferências.',
    previsaoEntrega: new Date('2025-09-05'),
    dataInicio: new Date('2025-08-28'),
    dataEntrega: new Date('2025-09-04'),
  },
  {
    id: 13,
    responsaveis: ['Tiago', 'Ursula'],
    urgencia: 'PRIORIDADE',
    status: 'PENDENTE',
    titulo: 'Aprimorar segurança de dados',
    descricao: 'Implementar criptografia de dados sensíveis.',
    previsaoEntrega: new Date('2025-09-06'),
    dataInicio: new Date('2025-08-29'),
    dataEntrega: new Date('2025-09-05'),
  },
  {
    id: 14,
    responsaveis: ['Vitor'],
    urgencia: 'ALTA',
    status: 'EM EXECUÇÃO',
    titulo: 'Otimizar consultas ao banco',
    descricao: 'Melhorar performance das queries SQL.',
    previsaoEntrega: new Date('2025-09-07'),
    dataInicio: new Date('2025-08-30'),
    dataEntrega: new Date('2025-09-06'),
  },
  {
    id: 15,
    responsaveis: ['Wesley', 'Xuxa'],
    urgencia: 'MEDIA',
    status: 'REVISÃO PENDENTE',
    titulo: 'Atualizar dependências do projeto',
    descricao: 'Atualizar pacotes NPM para versões mais recentes.',
    previsaoEntrega: new Date('2025-09-08'),
    dataInicio: new Date('2025-08-31'),
    dataEntrega: new Date('2025-09-07'),
  },
  {
    id: 16,
    responsaveis: ['Yara'],
    urgencia: 'BAIXA',
    status: 'CONCLUÍDA',
    titulo: 'Criar componente de alerta',
    descricao: 'Componente reutilizável para alertas do sistema.',
    previsaoEntrega: new Date('2025-09-09'),
    dataInicio: new Date('2025-09-01'),
    dataEntrega: new Date('2025-09-08'),
  },
  {
    id: 17,
    responsaveis: ['Zeca', 'Ana'],
    urgencia: 'PRIORIDADE',
    status: 'APROVADA',
    titulo: 'Implementar exportação de dados',
    descricao: 'Permitir exportar dados em CSV e PDF.',
    previsaoEntrega: new Date('2025-09-10'),
    dataInicio: new Date('2025-09-02'),
    dataEntrega: new Date('2025-09-09'),
  },
  {
    id: 18,
    responsaveis: ['Bruno'],
    urgencia: 'ALTA',
    status: 'CANCELADA',
    titulo: 'Adicionar suporte a temas',
    descricao: 'Permitir alternar entre tema claro e escuro.',
    previsaoEntrega: new Date('2025-09-11'),
    dataInicio: new Date('2025-09-03'),
    dataEntrega: new Date('2025-09-10'),
  },
  {
    id: 19,
    responsaveis: ['Carla', 'Eduardo'],
    urgencia: 'MEDIA',
    status: 'PENDENTE',
    titulo: 'Criar tutorial de onboarding',
    descricao: 'Guia passo a passo para novos usuários.',
    previsaoEntrega: new Date('2025-09-12'),
    dataInicio: new Date('2025-09-04'),
    dataEntrega: new Date('2025-09-11'),
  },
  {
    id: 20,
    responsaveis: ['Fernanda'],
    urgencia: 'BAIXA',
    status: 'EM EXECUÇÃO',
    titulo: 'Ajustar layout do rodapé',
    descricao: 'Melhorar visual do rodapé do site.',
    previsaoEntrega: new Date('2025-09-13'),
    dataInicio: new Date('2025-09-05'),
    dataEntrega: new Date('2025-09-12'),
  },
];

export const funcionarios: string[] = ['Fernanda', 'Carla', 'Eduardo', 'Bruno', 'Zeca', 'Ana', 'Yara', 'Wesley', 'Xuxa', 'Vitor', 'Tiago', 'Ursula', 'Sofia', 'Quésia', 'Rafael', 'Paulo', 'Nina', 'Otávio', 'Marina', 'João', 'Lucas', 'Isabela', 'Gabriel', 'Helena', 'Carlos']
